language: python
python: "3.5"

sudo: required

before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
  - sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
  - git submodule update --init --recursive

after_failure:
  - cat ghostdriver.log

install: 
  - "rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 6"
  - "cd frontend && nvm use 6 && npm install && npm run build"
  - "pip install -r ../integration_tests/requirements.txt"
script: 
  - set -e && set -o pipefail && phantomjs --version | tee /dev/stderr | grep 2.0.0
  - set -e  && set -o pipefail && ! npm run test 2>&1 | tee /dev/stderr | grep "Warning"
  - npm run lint
  - cd ../integration_tests && py.test -x --strict -r w --timeout=60
notifications:
  email:
    on_success: change
    on_failure: always
