language: python
python: "3.5"

before_install:
  - gem install sass

install: 
  - "rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 6"
  - "cd frontend && nvm use 6 && npm install && npm run build"
  - "pip install -r ../integration_tests/requirements.txt"
script: 
  - set -e  && set -o pipefail && npm run test | tee /dev/stderr | grep -v "Warning"
  - npm run lint
  - cd ../integration_tests && py.test
notifications:
  email:
    on_success: change
    on_failure: always
