export const ADD_ORDER_CUSTOMER = 'ADD_ORDER_CUSTOMER';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SELECT_MENU = 'SELECT_MENU';
